-- Q1

SELECT CODE, MOY_TEST FROM NOTATION, ETUDIANT
WHERE ETUDIANT.NUM_ET = NOTATION.NUM_ET
AND NOM_ET = 'ROCCHI' AND PRENOM_ET = 'STEPHANE'
ORDER BY MOY_TEST DESC;

SELECT CODE, MOY_TEST FROM NOTATION
JOIN ETUDIANT 
ON ETUDIANT.NUM_ET = NOTATION.NUM_ET
WHERE NOM_ET = 'ROCCHI' AND PRENOM_ET = 'STEPHANE'
ORDER BY MOY_TEST DESC;

SELECT CODE, MOY_TEST FROM NOTATION
WHERE NUM_ET = (
    SELECT NUM_ET FROM ETUDIANT
    WHERE NOM_ET = 'ROCCHI'
    AND PRENOM_ET = 'STEPHANE'
)
ORDER BY MOY_TEST DESC;

-- Q2

SELECT DISTINCT MODULE.CODE, LIBELLE FROM MODULE, ENSEIGNT, PROF
WHERE ENSEIGNT.CODE = MODULE.CODE
AND ENSEIGNT.NUM_PROF = PROF.NUM_PROF
AND NOM_PROF = 'BOITARD';

SELECT DISTINCT MODULE.CODE, LIBELLE FROM ENSEIGNT
JOIN MODULE ON ENSEIGNT.CODE = MODULE.CODE
JOIN PROF ON ENSEIGNT.NUM_PROF = PROF.NUM_PROF
WHERE NOM_PROF = 'BOITARD';

-- Q3

SELECT GROUPE FROM ETUDIANT, ENSEIGNT, PROF
WHERE ENSEIGNT.NUM_PROF = PROF.NUM_PROF
AND ENSEIGNT.NUM_ET = ETUDIANT.NUM_ET
AND PROF.NOM_PROF = 'LAPORTE'
AND PROF.PRENOM_PROF = 'MARC'
AND ETUDIANT.ANNEE = 2;

SELECT DISTINCT GROUPE FROM ENSEIGNT
JOIN PROF ON ENSEIGNT.NUM_PROF = PROF.NUM_PROF
JOIN ETUDIANT ON ENSEIGNT.NUM_ET = ETUDIANT.NUM_ET
AND PROF.NOM_PROF = 'LAPORTE'
AND PROF.PRENOM_PROF = 'MARC'
AND ETUDIANT.ANNEE = 2;

-- Q4

SELECT DISTINCT NOM_ET FROM ETUDIANT, MODULE, ENSEIGNT
WHERE ETUDIANT.NUM_ET = ENSEIGNT.NUM_ET
AND ENSEIGNT.NUM_PROF = RESP
ORDER BY NOM_ET;

-- Q5

SELECT DISTINCT NOM_ET FROM ETUDIANT, MODULE, ENSEIGNT
WHERE ETUDIANT.NUM_ET = ENSEIGNT.NUM_ET
AND ENSEIGNT.NUM_PROF = RESP
AND ENSEIGNT.CODE = MODULE.CODE
ORDER BY NOM_ET;

-- Q6

SELECT COUNT(*) FROM PROF;

-- Q7

SELECT AVG(MOY_CC) FROM NOTATION WHERE CODE = 'PRL';

-- Q8

SELECT COUNT(DISTINCT NUM_PROF) FROM ENSEIGNT, ETUDIANT
WHERE ENSEIGNT.NUM_ET = ETUDIANT.NUM_ET
AND NOM_ET = 'LYON';

-- Q9

SELECT AVG(NVL(
    (COEFF_CC * MOY_CC + COEFF_TEST * MOY_TEST) / (COEFF_CC + COEFF_TEST), 0
)) MOYENNE
FROM NOTATION, MODULE
WHERE NOTATION.CODE = MODULE.CODE
AND LIBELLE = 'PROLOG';

-- Q10

SELECT MAX(COEFF_TEST) FROM MODULE;

-- Q11

SELECT LIBELLE FROM MODULE
WHERE COEFF_TEST IN (
    SELECT MIN(COEFF_TEST) FROM MODULE
);

-- Q12

SELECT AVG(
(NVL(COEFF_CC, 0) * NVL(MOY_CC, 0) + NVL(COEFF_TEST, 0) * NVL(MOY_TEST, 0)) / (NVL(COEFF_CC, 0) + NVL(COEFF_TEST, 0))
) MOYENNE
FROM ETUDIANT, MODULE
WHERE NUM_ET = (
    SELECT NUM_ET FROM ETUDIANT
    WHERE NOM_ET = 'LEVY'
    AND PRENOM_ET = 'SANDRINE'
);

-- Q13




